### ISSUE TITLE
Apologies in advance -- can't find an e-mail, wanted to talk about HyperCard!

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [depp/keycode#7]
Hi-hi! So sorry for posting this in a place where it doesn't even remotely go, but I can't find your e-mail address anywhere or any other easy way of contacting you, so this seemed like to the most viable option. I'm a fellow HyperCard fan, and I was blown away to find your wonderful little write-up about the continued elegance and creative potential of the medium. The fact that you put both of my favourite indie HyperCard games in the same article AND knew the same esoteric factoids about them was an almost out-of-body experience.

For the past few years, with the permission of Andrew Griffin, I've been doing a remake of Get Rich Quick, actually. ^_^ ... into the incredibly dead medium that is Flash & AS3.

https://www.skyetheguy.com/GRQDemoPlay.html

But, hey, how was I to know that the death of Flash was impending when I started? That's actually one of the reasons I'm popping in. (Besides just geeking out.) Since you're championing the magic of HyperCard, and seem to be... just unfathomably smart about this kind of stuff, I wanted to pick your brain about what someone who likes making games in HyperCard and Flash might be able to do, moving forward, to keep making games that'll be accessible to play. Anyway, I apologize, again, for just dumping this here. If there's any chance of you responding to this, my e-mail is legotronn2@gmail. And MAN, your games and music are just the raddest-- thanks for making the Internet way cooler since the '90s.

**Comment by depp** [comment]
Hi! You can

**Comment by depp** [comment]
Hi! Maybe I'll add contact info to my website or something. Anyway, sent you an email.
